---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: tcr-ns
spec:
  selector:
    matchLabels:
      app: tcr-app
      tier: postgres
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: tcr-app
        tier: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          resources:
            limits:
              memory: 70Mi
            requests:
              memory: 50Mi
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-conf
          env:

           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: username

           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: password


          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: tcr-ns
  labels:
    app: tcr-app
    tier: postgres
spec:
  ports:
   - port: 5432
     targetPort: 5432
     #nodePort: 31002
  selector:
    app: tcr-app
    tier: postgres
  type: ClusterIP


---
# secret

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: tcr-ns
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: dGFsYW4yMDIy


---
# storage

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: tcr-ns
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: tcr-ns
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
                           
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
  namespace: tcr-ns
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: username
